In [8]:
x = 0.1
with open("./tmp/test.fox", "w") as f:
    f.write(
        f"""
INCLUDE 'COSY';

PROCEDURE run;

    OPENF 1234 './tmp/hello.txt' 'REPLACE';
    OV 5 3 0;
    RPE 16;
    UM;
    M5 {x} 1.0 0.0 0.0 0.0 0.0 0.05;
    PM 1234;
    CLOSEF 1234;

ENDPROCEDURE;

run;

END;

""".strip()
    )

import os
import fs
the_pid = os.spawnv(os.P_NOWAIT,"./cosy",[fs.path.abspath("./"),"./tmp/test.fox"])

print("boop")
os.waitpid(the_pid,0)

boop
                        
                        
                        
                        
                       ************************************
                       *                                  *
                       *    C O S Y    I N F I N I T Y    *
                       *                                  *
                       *       FOXY LANGUAGE SYSTEM       *
                       *                                  *
                       *           VERSION  10.2          *
                       *                                  *
                       *           (C) MSU 2022           *
                       *                                  *
                       ************************************
                        
                        
                        
                        
 ./tmp/test                                                                     
 --- BEGINNING COMPILATION 
 --- BIN FILE READ: COSY
 

(177656, 0)

In [ ]:
# import __init__ as cosy

# cosy.eval_fox(cosy.content_subs("""

# INCLUDE 'COSY';

# PROCEDURE run;

#     OPENF 1234 './tmp/hello.txt' 'REPLACE';
#     OV 5 3 0;
#     RPE 16;
#     UM;
#     M5 {{x}} 1.0 0.0 0.0 0.0 0.0 0.05;
#     DL 0.1;
#     PM 1234;
#     CLOSEF 1234;

# ENDPROCEDURE;

# run;

# END;
                  
# """,{"x":0.1}))()

In [2]:
import __init__ as cosy

print(cosy.eval_fox(cosy.content_subs("""
OV 5 3 0;
RPE 16;
UM;
M5 {{x}} 1.0 0.0 0.0 0.0 0.0 0.05;
DL 0.1;
PM 0;          
""",{"x":0.1}))())

   9.706861      62.69172      0.000000      0.000000      0.000000     100000
  0.5163227      3.437688      0.000000      0.000000      0.000000     010000
   0.000000      0.000000     -2.128990     -17.99946      0.000000     001000
   0.000000      0.000000     0.1663769E-01-0.3290437      0.000000     000100
   0.000000      0.000000      0.000000      0.000000      1.000000     000010
   0.000000      0.000000      0.000000      0.000000     0.1802390E-03 000001
   0.000000      0.000000      0.000000      0.000000     -234.0643     200000
   0.000000      0.000000      0.000000      0.000000     -26.15096     110000
   0.000000      0.000000      0.000000      0.000000    -0.7412410     020000
   0.000000      0.000000      0.000000      0.000000     -25.95919     002000
   0.000000      0.000000      0.000000      0.000000    -0.1420009     001100
  -12.13835     -30.16893      0.000000      0.000000      0.000000     100001
 -0.8879089     -3.040486      0.000000      0.00000

In [5]:
import __init__ as cosy

txt = cosy.eval_fox(cosy.content_subs("""
OV 5 3 0;
RPE 16;
UM;
M5 {{x}} 1.0 0.0 0.0 0.0 0.0 0.05;
DL 0.1;
PM 0;
WRITE 0 'a' 0.4;
WRITE 0 'b' 0.4;
""",{"x":0.1}))()
v0, txt = cosy.parse_transfer_map(txt)
v1, txt = cosy.parse_write_dict(txt)
v0([0,0.01,0,0,0,0]),v1

(array([ 5.16607947e-03,  3.43803810e-02,  0.00000000e+00,  0.00000000e+00,
        -7.41956589e-05]),
 {'a': np.float64(0.4), 'b': np.float64(0.4)})

In [10]:
import typing
import subprocess
import fs
import numpy as np
import numpy.typing as npt


def parse_transfer_map(
    src: str,
) -> tuple[typing.Callable[[npt.NDArray], npt.NDArray],str]:
    """
    Read in a cosy transfer map, returning the function that it represents.

    `(x,a,y,b,t,K) -> (x,a,y,b,t)`
    """
    src_end_i = src.find("----")
    if src_end_i == -1:
        raise ValueError("map data invalid")
    src, rem = src[:src_end_i], src[src.find("\n", src_end_i) :]

    map_data = [
        (
            np.array(
                [
                    float(line[1 + 0 * 14 : 1 + 1 * 14]),
                    float(line[1 + 1 * 14 : 1 + 2 * 14]),
                    float(line[1 + 2 * 14 : 1 + 3 * 14]),
                    float(line[1 + 3 * 14 : 1 + 4 * 14]),
                    float(line[1 + 4 * 14 : 1 + 5 * 14]),
                ]
            ),
            [int(v) for v in line[2 + 5 * 14 :]],
        )
        for line in src.splitlines()
        if line.strip() != ""
    ]
    def eval_map(args:npt.ArrayLike):
        return sum(
            row * np.prod(np.power(args, basis_powers))
            for row, basis_powers in
            map_data
        )
    return eval_map, rem


with open("./tmp/hello.txt", "r") as f:
    v,_ = parse_transfer_map(f.read())

v([0.1,0.0,0.0,0.0,0.0,0.0])

array([502.5731561, 161.723772 ,   0.       ,   0.       , -72.854913 ])

In [11]:
import __init__ as cosy
with open("./tmp/hello.txt", "r") as f:
    v,_ = cosy.parse_transfer_map(f.read())

v([0.1,0.0,0.0,0.0,0.0,0.0])

array([502.5731561, 161.723772 ,   0.       ,   0.       , -72.854913 ])

In [2]:
import __init__ as cosy


txt = """

hello
  2.000000000000000     
  2.000000000000000     
world
  2.000000000000000 
world2
world3
  2.000000000000000 
  2.000000000000000 
  2.000000000000000 

world4
  2.000000000000000 

""".strip()

# txt = txt.strip().replace("\r","")
# i = txt.find("\n")
# k = txt[:i]
# v = []
# while len(txt) > i+1 and txt[i+1] == " ":
#     i_end = txt.find("\n",i+1)
#     v.append(float(txt[i:i_end]))
#     i=i_end
# rem = txt[i_end+1:]
# k,v,rem

# k0,v0, txt = cosy.parse_write(txt)
# k1,v1, txt = cosy.parse_write(txt)

# {k0:v0,k1:v1}

# cosy.parse_write_dict(txt, reduce_single=False)
cosy.parse_write_dict(txt)

{'hello': array([2., 2.]),
 'world': np.float64(2.0),
 'world2': array([], dtype=float64),
 'world3': array([2., 2., 2.])}